config/routes.rb
Rails.application.routes.draw do
  get 'posts/filter', to: "posts#index"
  resources :topics
  resources :ratings
  resources :offers
  resources :posts
  resources :reservations
  resources :users

  get '/', to: "sessions#welcome", as: "welcome"
  get '/signin', to: "sessions#new", as: "signin"
  post '/', to: "sessions#secret", as: "secret"
  delete '/', to: "sessions#destroy", as: "logout"
  get '/slack/auth', to: "sessions#create", as: "slack_login"

  get '/users/:id/ratings', to: "users#ratings", as: "user_ratings"
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts, foreign_key: "student_id"
	has_many :student_reservations, class_name: "Reservation", foreign_key: "student_id"
	has_many :tutor_reservations, class_name: "Reservation", foreign_key: "tutor_id"
	has_many :offers, foreign_key: "tutor_id"
	has_many :ratings, through: :tutor_reservations

	validates :username, :first_name, :last_name, :email, :slack_id, presence: true

	def full_name
		[self.first_name, self.last_name].join(" ")
	end

	def avg_rating
		if self.ratings.present?
			self.ratings.pluck(:value).map(&:to_f).reduce(:+)/self.ratings.count
		else
			"N/A"
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:message] = "You've successfully signed up for Food For Thought!"
			redirect_to posts_path
		else
			flash[:message] = "Please fill-in all values!"
			render :new
		end
	end

	def show
		@user = User.find_by(id: params[:id])
	end

	def edit
		@user = User.find(session[:user_id])
	end

	def update
		@user = User.find(session[:user_id])
		@user.update(user_params)

		redirect_to user_path(@user)
	end

	def ratings
		@user = User.find_by(id: params[:id])
		
	end

	private

	def user_params
		params.require(:user).permit(:username, :first_name, :last_name, :email, :description, :slack_id, :small_picture, :profile_picture)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="panel panel-default col-md-4">
<h1>Edit Profile</h1>
<%= form_for @user do |f|%>

	<div class="form-group"> 
		<%= f.label :first_name%><br>
		<%= f.text_field :first_name, class: "form-control"%>
	</div>

	<div class="form-group"> 
		<%= f.label :last_name %><br>
		<%= f.text_field :last_name, class: "form-control"%>
	</div>

	<div class="form-group"> 
		<%= f.label :email %><br>
		<%= f.text_field :email, class: "form-control"%>
	</div>

	<div class="form-group"> 
		<%= f.label :description %><br>
		<%= f.text_area :description, class: "form-control", rows: "6"%>
	</div>

	<%= f.submit "Update Profile", class: "btn btn-primary form-control"%>

	<br><br>


<% end %>
</div>

<div class="col-md-8">
	<img class="img-responsive" src="https://www.visitbratislava.com/wp-content/uploads/2016/07/title-photo_bratislavafoodtour-800x800.jpg">
</div>

<!-- change -->

app/views/users/new.html.erb
<div class="panel panel-default col-md-4">
<h1>Sign up!</h1>
<%= flash[:message]%>
<%= form_for @user do |f|%>
	
	<div class="form-group"> 
		<%= f.label :first_name%><br>
		<%= f.text_field :first_name, class: "form-control"%>
	</div>

	<div class="form-group"> 
		<%= f.label :last_name %><br>
		<%= f.text_field :last_name, class: "form-control"%>
	</div>


	<div class="form-group"> 
		<%= f.label :email %><br>
		<%= f.text_field :email, class: "form-control"%>
	</div>

	<div class="form-group"> 
		<%= f.label :description %><br>
		<%= f.text_area :description, class: "form-control", rows: "6"%>
	</div>

	<%= f.hidden_field :slack_id %>
	<%= f.hidden_field :username %>
	<%= f.hidden_field :small_picture %>
	<%= f.hidden_field :profile_picture %>

	<%= f.submit "Create Profile", class: "btn btn-primary form-control"%>

	<br><br>


<% end %>
</div>

<div class="col-md-8">
	<img class="img-responsive" src="https://www.visitbratislava.com/wp-content/uploads/2016/07/title-photo_bratislavafoodtour-800x800.jpg">
</div>

app/views/users/ratings.html.erb
<div class="col-md-4">
  <% @user.ratings.each do |rating| %>
    <div class="row">
      <div class="panel panel-default" style="padding: 10px;margin-bottom: 5px;margin-top: 5px;">
      <p><strong>Rating: </strong> <%= "★" * rating.value.to_i %><%= "☆" * (5 - rating.value.to_i) %></p>
      <p><strong>Comment: </strong><%= rating.comment %></p><br>
    </div>
  </div>
<% end %>
</div>

<div class="col-md-8">
	<div class="jumbotron" style="background-image: url(<%=asset_path('new_post_img.jpg')%>);  background-size: cover; min-height: 730px">
	<br><br><br>
		<div style = "background-color: rgba(0,0,0,0.1); ">
			<p style=" color: white; font-size: 500%" >Do your peers ACTUALLY like you? <strong style="color: white" >Well, now you know.</strong></p>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="panel panel-default col-md-12">

	<div class="col-md-4">
		<h1><%=@user.full_name%></h1>
		<img src="<%=@user.profile_picture%>" class="img-rounded" height="300" width="300"><br>
		<h4><i class="fa fa-user fa-lg"></i>&nbsp;&nbsp;<%= @user.username%></h4>
		<h5><i class="fa fa-envelope fa-lg"></i>&nbsp;&nbsp;<%= @user.email%></h5>
		<% if @user.ratings.present? %>
			<h4>Average rating: <%= @user.avg_rating.to_s[0..3] %> (<%= link_to "All ratings", user_ratings_path%>)</h4>
		<% end %>
		<div class="col-md-6">
			<%= button_to "Edit info", edit_user_path(@user), method: :get, class: "btn btn-primary btn-xs", style: "position: relative;left: -15px;"%>
		</div>
		<br><br>
	</div>

	<div class="row col-md-8" style="margin-top: 66px;">
		<div class="col-md-6" style="min-height: 220px;">
			<h3 style="margin-top: 10px;">Posts</h3>
			<div class="table">
				<% @user.posts.each do |post|%>
					<p><%= link_to post.title, post_path(post)%> | Status: <%=post.status%></p>
				<% end %>
			</div>
		</div>
		<div class="col-md-6" style="min-height: 220px">
			<div>
				<h3 style="margin-top: 10px;">Teaching sessions</h3>
			</div>
			<% @user.tutor_reservations.each do |reservation|%>
				<% unless reservation.status == "reviewed" %>
					<div class="panel-default jumbotron" style="padding: 8px;margin-bottom: 5px;margin-top: 5px;">
						<p><%= link_to reservation.post.title, post_path(reservation.post)%></p>
						<%= form_for reservation, url: reservation_path(reservation), method: :delete do |f|%>
							<%= f.button "Cancel session", class: "btn btn-sm btn-danger"%>
						<% end %>
					</div>
				<% end %>
			<% end %>
		</div>
		
</div>
	<div class="row col-md-8" >
		<div class="col-md-6" style="min-height:220px">
			<% if @user.id == current_user.id %>
			<div>
				<div>
					<h3 style="margin-top: 10px;">Pending offers</h3>
				</div>
				<% @user.offers.each do |offer|%>
					<p><%= link_to offer.post.title, post_path(offer.post)%></p>
				<% end %>
			</div>
			<% end %>
		</div>
			
			<div class="col-md-6">
			<h3 style="margin-top: 10px;">Learning sessions</h3>
			<% @user.student_reservations.each do |reservation|%>
				<% unless reservation.status == "reviewed" %>
					<div class="panel-default jumbotron" style="padding: 8px;margin-bottom: 5px;margin-top: 5px;">
						<p><%= link_to reservation.post.title, post_path(reservation.post)%></p>
						<div class="d-inline">
							<%= form_for :review, url: new_rating_path, method: :get do |f| %>
								<%= f.button "Review tutor", value: reservation.tutor.id, class: "btn btn-sm btn-success"-%>
								<%= f.hidden_field :reservation_id, value: reservation.id %>
							<% end %>
						</div>
						<div class="d-inline">
							<%= form_for reservation, url: reservation_path(reservation), method: :delete do |f|%>
								<%= f.button "Cancel session", class: "btn btn-sm btn-danger"%>
							<% end %>
						</div>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>