config/routes.rb
Rails.application.routes.draw do
  get 'posts/filter', to: "posts#index"
  resources :topics
  resources :ratings
  resources :offers
  resources :posts
  resources :reservations
  resources :users

  get '/', to: "sessions#welcome", as: "welcome"
  get '/signin', to: "sessions#new", as: "signin"
  post '/', to: "sessions#secret", as: "secret"
  delete '/', to: "sessions#destroy", as: "logout"
  get '/slack/auth', to: "sessions#create", as: "slack_login"

  get '/users/:id/ratings', to: "users#ratings", as: "user_ratings"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :student, class_name: "User", foreign_key: "student_id"
  has_many :offers
  has_many :reservations
  belongs_to :topic

  validates :deadline, :title, :description, :compensation, :topic, presence: true
  validate :valid_date

  def topic_attributes=(top)
	  self.topic = Topic.find_by(top)
	  self.save
  end

  def valid_date
    if deadline.blank? || deadline < Date.today
      errors.add(:deadline, "Date is not valid")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	STOCK_PHOTOS = [
		"stock_photo1.jpg",
		"stock_photo2.jpg",
		"stock_photo3.jpg",
		"stock_photo4.jpg",
		"stock_photo5.jpg",
		"stock_photo6.jpg",
		"stock_photo7.jpg",
		"stock_photo8.jpg",
		"stock_photo9.jpg"
	]

	before_action :require_login

	def index
		@posts = Post.all
		@user = User.find(session[:user_id])
		@topics = Topic.all.to_a
		@topics.unshift(Topic.new(name: "All"))
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.student = User.find(session[:user_id])

		if @post.picture_path.blank?
			@post.picture_path = STOCK_PHOTOS.sample
		end
			if @post.save
				flash[:message] = "Thanks for submitting a post, help is on the way!"
				redirect_to post_path(@post)
			else
				flash[:message] = "Hey! You missed something!"
				render :new
			end
	end

	def filter
		@topics = Topic.all.to_a
		@topics.unshift(Topic.new(name: "All"))
		@posts = Post.where(topic_id: Topic.find_by(name: params["topics"]))
		@posts = Post.all if params["topics"] == "All"
		render :index

	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find_by(id: params[:post_id])
	end

	def update
		@post = Post.find_by(id: params[:id])
		@post.update(post_params)
		flash[:message] = "Good job gettin' your edit on!"
		redirect_to posts_path(@post)

	end

	def destroy
		@post = Post.find_by(id: params[:id])
		@post.destroy
		redirect_to posts_path
	end

	# def message_user
	# 	token = "token=xoxp-2727337933-202554058455-220319981716-935148097c1ac783a1e4ee0afc3a08c6&channel=G6G56GYSF"
	# 	base_url = "https://slack.com/api/chat.postMessage?"
	# 	message = params[:message] # message
	# 	channel = 'channel=' + ''# Post.user.slack
	# 	full_request_url = base_url + token + channel + message
	# # request = RestClient.get(url)
 # 	# parse = JSON.parse(request)
	# end

	private

	def post_params
		params.require(:post).permit(:topic, :title, :compensation, :length, :deadline, :description, :picture_path, topic_attributes: [:id])
	end
end




# TODO
# send slack reminder after reservation created
# search for slash commands
# '/remind me in 10 minutes to drink a glass of water'
#
#
# SEND INVITATION SEACH MENU BUTTONS
# {
#     "text": "Hey! Name_of_tutor would like to be your tutor.",
#     "attachments": [
#         {
#             "text": "Choose a game to play",
#             "fallback": "You are unable to choose a game",
#             "callback_id": "wopr_game",
#             "color": "#3AA3E3",
#             "attachment_type": "default",
#             "actions": [
#                 {
#                     "name": "accept_request",
#                     "text": "Accept",
#                     "type": "button",
# 					"style": "primary",
#                     "value": "accepted"
#                 },
#                 {
#                     "name": "deny_request",
#                     "text": "Deny",
#                     "style": "danger",
#                     "type": "button",
#                     "value": "denied",
#                     "confirm": {
#                         "title": "Are you sure?",
#                         "text": "Wouldn't you prefer a good game of chess?",
#                         "ok_text": "Yes",
#                         "dismiss_text": "No"
#                     }
#                 },
# 				                {
#                     "name": "review_request",
#                     "text": "Review Request",
#                     "type": "button",
#                     "value": "review"
#                 }
#             ]
#         }
#     ]
# }

# CREATE REMINDER
# reminders.add
# reminders.complete
# reminders.delete

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="panel panel-default col-md-4">
<h1>Edit Post</h1>
<%= form_for @post do |f|%>

	<div class="form-group">
		<%= f.label :title %><br>
		<%= f.text_field :title, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.fields_for :topic_attributes do |t|%>
			<%= t.label :topic %><br>
			<%= t.select :id, Topic.all.collect{ |t| [ t.name, t.id ] }, include_blank: true%>
		<% end %>
	</div>

	<div class="form-group">
		<%= f.label :description %><br>
		<%= f.text_area :description, class: "form-control", rows: "6"%>
	</div>

	<div class="form-group">
		<%= f.label :compensation%><br>
		<%= f.text_field :compensation, class: "form-control"%>
	</div>

	<div class="form-group">
		<%= f.label :length %><br>
		<%= f.text_field :length, class: "form-control"%>
	</div>

	<div class="form-group">
		<%= f.label :deadline %><br>
		<%= f.date_field :deadline, class: "form-control"%>
	</div>



	<div class="form-group">
		<%= f.label "Link to a picture" %><br>
		<%= f.text_field :picture_path, class: "form-control"%>
	</div>



	<%= f.submit "Edit Post", class: "btn btn-primary form-control" %><br>
<% end %>
	<%= button_to  "Delete Post", @post, class: "btn btn-danger form-control", style: "margin-top: 6px", method: :delete, data: {confirm: "Are you sure you want to delete your post?"}%>

	<br>


</div>

<div class="col-md-8">
	<div class="jumbotron" style="background-image: url(<%=asset_path('new_post_img.jpg')%>);  background-size: cover; min-height: 730px">
	<br><br><br>
		<div style = "background-color: rgba(0,0,0,0.1); ">
			<p style=" color: white; font-size: 500%" >Passing the assessment? <strong style="color: white" >Probably worth a burrito.</strong></p>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
        <header class="jumbotron hero-spacer" style="background-image: url(<%=asset_path('pizza2.jpg')%>);  background-size: cover; background-position-y: 27%;background-repeat: no-repeat;">
                <h1 style="display: inline-block; color: white; background-color: rgba(0,0,0,0.1);">Help is here!</h1>
                <p style="color: white; background-color: rgba(0,0,0,0.1); width: 280px;">Get started with a new post!</p>

                <p><%= link_to "New post", new_post_path, class: "btn btn-primary btn-large"%></p>
        </header>
        <hr>

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3 class="d-inline" >All Posts</h3>
            <div class="pull-right">
                <div class="d-inline"><p>filter by topics:</p>
                </div>
                <div class="d-inline"><%= form_tag filter_path do %>
                    <div class="d-inline">
                    <%= select_tag "topics", options_from_collection_for_select(@topics, "name", "name"), class: "form-control"%>
                    </div>
                    <%= submit_tag 'search', class: 'btn btn-info' %>
                <% end %>
                </div>
            </div>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <div class="row text-center">

            <% i = 0 %>
            <% @posts.each do |post|%>
                <% unless post.status != "open"%>
                    <%= raw "<div class='row'>" if i%4 == 0%>
    		            <div class="col-md-3 hero-feature">
    		                <div class="thumbnail">
                            <img src="<%=post.student.profile_picture%>" width="800" height="500">
    		                    <div class="caption">
    		                        <h4><%= link_to post.title, post_path(post)%></h4>
    		                        <p><%= post.description[0..15] + "..."%></p>
    		                            <%= form_for post, url: offers_path, :html => {class: 'd-inline'} ,method: :post do |f|%>
    										<%= f.button "Offer help", name: :post_id, class: "btn btn-primary", value: post.id, data: {confirm: "Are you sure you want to offer help?"}%>
    									<% end %>
    		                            <a href="<%=post_path(post)%>" class="btn btn-default">More info</a>
    		                    </div>
    		                </div>
    		            </div>
                    <%= raw "</div>"if i%4 == 3%>
                    <%i += 1%>
	          	<% end %>
	        <% end %>

app/views/posts/new.html.erb
<div class="panel panel-default col-md-4">
<h1>Create New Post</h1>
<%= form_for @post do |f|%>

	<div class="form-group"> 
		<%= f.label :title %><br>
		<%= f.text_field :title, class: "form-control" %>
	</div>

	<div class="form-group"> 
		<%= f.fields_for :topic_attributes do |t|%>
			<%= t.label :topic %><br>
			<%= t.select :id, Topic.all.collect{ |t| [ t.name, t.id ] }, include_blank: true%>
		<% end %>
	</div>

	<div class="form-group"> 
		<%= f.label :description %><br>
		<%= f.text_area :description, class: "form-control", rows: "6"%>
	</div>

	<div class="form-group"> 
		<%= f.label :compensation%><br>
		<%= f.text_field :compensation, class: "form-control"%>
	</div>

	<div class="form-group"> 
		<%= f.label :length %><br>
		<%= f.text_field :length, class: "form-control"%>
	</div>

	<div class="form-group"> 
		<%= f.label :deadline %><br>
		<%= f.date_field :deadline, class: "form-control"%>
	</div>



	<div class="form-group"> 
		<%= f.label "Link to a picture" %><br>
		<%= f.text_field :picture_path, class: "form-control"%>
	</div>



	<%= f.submit "Create New Post", class: "btn btn-primary form-control"%>

	<br><br>


<% end %>
</div>

<div class="col-md-8">
	<div class="jumbotron" style="background-image: url(<%=asset_path('new_post_img.jpg')%>);  background-size: cover; min-height: 730px">
	<br><br><br>
		<div style = "background-color: rgba(0,0,0,0.1); ">
			<p style=" color: white; font-size: 500%" >Passing the assessment? <strong style="color: white" >Probably worth a burrito.</strong></p>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="panel panel-default col-md-12">

	<div class="col-md-3">
		<h3><%=@post.title%></h3>

		<text><strong>Student: </strong><%= link_to @post.student.username, user_path(@post.student) %></text><br>
		<text><strong>Topic: </strong><%= @post.topic.name%></text><br>
		<text><strong>Length: </strong><%= @post.length%></text><br>
		<text><strong>Compensation: </strong><%= @post.compensation%></text><br>
		<text><strong>Deadline: </strong><%= @post.deadline.strftime("%m/%d/%Y")%></text><br>
		<text><strong>Description: </strong><%=@post.description%></text>
		<br><br>
		<% if @post.student == current_user %>
			<%= (button_to "Edit post", edit_post_path(@post), params: {post_id: @post.id}, method: :get, class: "btn btn-primary") %>
		<% else %>
			<%= (button_to "Offer your help!", offers_path, params: {post_id: @post.id}, method: :post, name: :post_id, class: "btn btn-primary") %>
		<% end %>
		<br>
	</div>



	<div class="col-md-4">
			<br><br>
			<h4><strong>Offers to this post</strong></h4>
			<% if @post.student == current_user %>
			<% @post.offers.each do |offer|%>
				<%= link_to offer.tutor.full_name, user_path(offer.tutor)%><br>
				<a href="https://flatiron-school.slack.com/messages/@<%=offer.tutor.username.gsub(" ", "_")%>", class= 'btn btn-success btn-sm' target ='_blank'%>Slack</a>
				<%= form_for :reservation, url: reservations_path, html: {class: 'd-inline'}, method: :post do |f|%>
					<%= f.button "Accept offer!", name: :offer_id, value: offer.id, class: "btn btn-warning btn-sm"%><br>
				<% end %>
				<br>
			<% end %>
			<% end %>
	</div>

	<div class="col-md-5">
		<br>
		<img src="<%=asset_path(@post.picture_path)%>" height="800" width="500" class = "img-responsive"><br>
	</div>