config/routes.rb
Rails.application.routes.draw do
  get 'posts/filter', to: "posts#index"
  resources :topics
  resources :ratings
  resources :offers
  resources :posts
  resources :reservations
  resources :users

  get '/', to: "sessions#welcome", as: "welcome"
  get '/signin', to: "sessions#new", as: "signin"
  post '/', to: "sessions#secret", as: "secret"
  delete '/', to: "sessions#destroy", as: "logout"
  get '/slack/auth', to: "sessions#create", as: "slack_login"

  get '/users/:id/ratings', to: "users#ratings", as: "user_ratings"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>FoodForThought</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Tab icon -->
    <%= favicon_link_tag 'favicon.ico' %>

  </head>


  <header>
    <nav class="container navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="<%= posts_path%>"><img id="logoOnHeader" class="animated fadeInUp"src="<%= asset_path('FFT_logo.png') %>" width="50" style="position: absolute;top: -1px;left: 25px;"><span style="position: relative;left: 47px;">food for thought</span></a>
        </div>
          <ul class="nav navbar-nav navbar-right">
            <%if logged_in?%>
            <li><a href="<%= new_post_path %>">New Post&nbsp;<i class="fa fa-plus fa-inverse"></i></a></li>

            <li class="dropdown avatar-holder">
              <img src="<%=current_user.small_picture%>" height="42" width="42" class="img-circle" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret" style="color: white"></span></a>
              <ul class="dropdown-menu">
                   <li><%= (link_to "My dashboard", user_path(current_user))%></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
              </ul>
            </li>
            <% end %>

          </ul>
        </div>
      </div>
    </nav>
    </header>
    <body id="body">
      <div class="container animated fadeIn">
        <% if flash[:message].present? %>
          <div class="alert alert-info">
            <p><%= flash[:message]%></p> 
          </div>
        <% end %>
      <%= yield %>

      </div>
      <div class="container">
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Food For Thought LLC 2017</p>
                </div>
            </div>
        </footer>
      </div>


  </body>

</html>